/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppHome {
    }
    interface AppProfile {
    }
    interface AppRoot {
    }
    interface ButtonLanding {
        "text": string;
    }
    interface HeaderTitle {
        "image": string;
        "text": string;
    }
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {
    }
    var HTMLAppProfileElement: {
        prototype: HTMLAppProfileElement;
        new (): HTMLAppProfileElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLButtonLandingElement extends Components.ButtonLanding, HTMLStencilElement {
    }
    var HTMLButtonLandingElement: {
        prototype: HTMLButtonLandingElement;
        new (): HTMLButtonLandingElement;
    };
    interface HTMLHeaderTitleElement extends Components.HeaderTitle, HTMLStencilElement {
    }
    var HTMLHeaderTitleElement: {
        prototype: HTMLHeaderTitleElement;
        new (): HTMLHeaderTitleElement;
    };
    interface HTMLElementTagNameMap {
        "app-home": HTMLAppHomeElement;
        "app-profile": HTMLAppProfileElement;
        "app-root": HTMLAppRootElement;
        "button-landing": HTMLButtonLandingElement;
        "header-title": HTMLHeaderTitleElement;
    }
}
declare namespace LocalJSX {
    interface AppHome {
    }
    interface AppProfile {
    }
    interface AppRoot {
    }
    interface ButtonLanding {
        "text"?: string;
    }
    interface HeaderTitle {
        "image"?: string;
        "text"?: string;
    }
    interface IntrinsicElements {
        "app-home": AppHome;
        "app-profile": AppProfile;
        "app-root": AppRoot;
        "button-landing": ButtonLanding;
        "header-title": HeaderTitle;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-profile": LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "button-landing": LocalJSX.ButtonLanding & JSXBase.HTMLAttributes<HTMLButtonLandingElement>;
            "header-title": LocalJSX.HeaderTitle & JSXBase.HTMLAttributes<HTMLHeaderTitleElement>;
        }
    }
}
